destination: ../master

name: CodeSolid

description:  Scala Development

meta_description: "Wherein my modest successes as a coder and spectacular failures as a community builder are documented in gruesome detail."

markdown: redcarpet

# pygments: false

encoding: utf-8


include: ['_pages', '_goalboost_testplan']

relative_permalinks: false

permalink: /:title

baseurl: "http://codesolid.com/"

post:
  template: templates/_post.txt
  extension: md

#editor: C:\apps\SublimeText3\sublime_text.exe
editor:	subl

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      author:  "John Lockwood"

paginate: 20
paginate_path: "blog/page:num"
